name: Testing GitHub-Script

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm install csv-parser
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-url: api.github.com
          script: |
            let csv = require('csv-parser')
            console.log(csv)
          
        
